### ISSUE TITLE
Could not install package 'Mantin.Controls.Wpf.Notification 3.2.0'		0	

### ISSUE THREAD

**Issue by HagenKnight** [accessguru/mantincontrols#1]
Hello

I'm trying to install the package from NuGet PM, from console and GUI PM and I get this error:

`Could not install package 'Mantin.Controls.Wpf.Notification 3.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

The same thing trying to install the EnumComboBox:
`Could not install package 'Mantin.Controls.Wpf.EnumComboBox 1.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

I'm using VS2015 Community Edition, my Project .NET framework is 4.5. What can I do?
Thanks

**Comment by accessguru** [comment]
Try changing your target framework to 4.6.  If that doesn't work let me know. I'm in Europe for two weeks and can't check at the moment.  

Lawrence Mantin

**Comment by HagenKnight** [comment]
All right, it Works! Upgrading my Project to .NET to 4.6 allows to install, . The strange thing is there's no declared dependencies on Nuget dialog box. Happy holidays!
